{
	"name": "CoronaVirus",
	"version": "1.0.7",
	"icon": "fas fa-biohazard",
	"category": "health",
	"author": "psycho",
	"maintainers": [],
	"desc": "Information about the spread of the virus, worldwide. Get your api key: https://rapidapi.com/KishCom/api/covid-19-coronavirus-statistics",
	"aliceMinVersion": "1.0.0-a6",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"de"
		]
	}
}

